### ISSUE TITLE
How to enter multiple hotspots in config

### ISSUE THREAD

**Issue by Niteowldev** [co8/HDS#26]
Is monitoring multiple hotspots an option?  When I list more than 1 hotspot in the config file I get an error.

**Comment by co8** [comment]
Hi. Single hotspot only. You can create multiple instances and run them individually

**Comment by co8** [comment]
duplicate the hds folder for each hotspot (eg hds, hds2). set config for each one. Then in crontab add a line for each instance script and log cleaner. They will run sequentially even though you set them all to run every minute

- one hds for each hotspot
/hds
/hds2

- crontab
*/1 * * * * cd /hds; python3 hds.py >> cron.log 2>&1
20 4 * * 1 cd /hds; rm cron.log;  echo 'Cron Log Cleared\n'  >> cron.log 2>&1
*/1 * * * * cd /hds2; python3 hds.py >> cron.log 2>&1
20 4 * * 1 cd /hds2; rm cron.log;  echo 'Cron Log Cleared\n'  >> cron.log 2>&1
