### ISSUE TITLE
Add command line arguments to filter status messages

### ISSUE THREAD

**Issue by rdomloge** [co8/HDS#33]
More of a feature request than an issue! I was wondering if you would consider adding some way to filter out specific types of events - particularly 'created challenge' or 'beacon with zero witnesses' or 'challenged hotspot'.

This could be done by command line arguments or extra fields in the JSON config.

**Comment by co8** [comment]
Thanks for the feedback! Yes, in future releases you'll be able to filter activity types via config or command line. Filtering is already a functionality in the HAPpy API parser. Once HDS uses HAPpy at its core filtering will be active.
