### ISSUE TITLE
Activity API: Bad Data , TypeError: unsupported operand type(s) for -: 'int' and 'NoneType'

### ISSUE THREAD

**Issue by dsimka** [co8/HDS#41]
First of all, thanks for you work!
I managed to run the code under debian linux with python3.7 and all requirements are met.
Sometimes i get "Activity API: Bad Data"
And i had "." in log which means no changes , but then , started printing errors, log follows, last error repeated many times.
The Hotspot is new - 11AeVjpWXZ3wVc4y4F48YxLwZeLet11hAvjxDCtcPUrDzso8trN

11:32 12/12/21 Activity API: Bad Data
...................
11:52 12/12/21 Activity API: Bad Data
Traceback (most recent call last):
  File "hds.py", line 899, in <module>
    main()
  File "hds.py", line 869, in main
    load_hotspot_data_and_status()
  File "hds.py", line 683, in load_hotspot_data_and_status
    block_gap_num = int(hs["block"] - hs["height"])
TypeError: unsupported operand type(s) for -: 'int' and 'NoneType'

**Comment by co8** [comment]
Thanks! I'm glad you like the work. 

The PoCv11 update, plus the demand on the public API, sometimes cause "bad data" errors when the response isn't proper JSON. HDS takes this into account and is logging the errors, but understands not to act. Most likely, when the API is up and running, you'll receive an HDS update with any activity (i got 16 in one response once) not reported yet.

Once PoCv11 is up and running stable.

Alternately, you could run your own ETL and API instance, and these issues should reduce significantly.

**Comment by relaxpn** [comment]
@dsimka @co8 
I've also experienced this error with one of the recently added hotspots.
Looks like the 'height' inside 'status' is null so the script is unable to determine the gap, hence the error.

![image](https://user-images.githubusercontent.com/9318570/147914693-de400595-e57e-453b-92ca-a96a907f7371.png)

**Comment by Alexxino** [comment]
I have the same error, how can we fix it ?  That's a pity! this project is cool

```
Traceback (most recent call last):
  File "hds.py", line 912, in <module>
    main()
  File "hds.py", line 882, in main
    load_hotspot_data_and_status()
  File "hds.py", line 696, in load_hotspot_data_and_status
    block_gap_num = int(hs["block"] - hs["height"])
TypeError: unsupported operand type(s) for -: 'int' and 'NoneType'
```

**Comment by dsimka** [comment]
If your spot is new, just wait. When it gets to synced status, everything will be OK
