### ISSUE TITLE
traceback error

### ISSUE THREAD

**Issue by Madnessx9** [co8/HDS#44]
```
 python3 hds.py
Traceback (most recent call last):
  File "/home/===/hds/hds.py", line 912, in <module>
    main()
  File "/home/===/hds/hds.py", line 886, in main
    local_bobcat_miner_report()
  File "/home/===/hds/hds.py", line 164, in local_bobcat_miner_report
    miner_block_int = int(data["blockchain_height"])
KeyError: 'blockchain_height'
```

followed every step twice, unable to get past this error, any ideas?

**Comment by co8** [comment]
This can happen for a newly activated hotspot that isn't yet on-chain, or on-chain without asserted location. 

The error stops once the hotspot block height is recorded on-chain. The API can be delayed and this data can be outdated.

This is related to another comment. I'll write in something to catch the error
