### ISSUE TITLE
Key Error when runnning

### ISSUE THREAD

**Issue by Chief-Zach** [co8/HDS#56]
I am getting a key error when running the code. 
The error is as follows: 

`File "hds.py", line 922, in <module>
    main()
  File "hds.py", line 893, in main
    loop_activities()
  File "hds.py", line 637, in loop_activities
    poc_receipts(activity)
  File "hds.py", line 532, in poc_receipts
    "challengee" in activity["path"][0]
KeyError: 'path'`

**Comment by co8** [comment]
Hi. What kind of hotspot are you using? Is the hotspot on-chain? Synced and Participating? FYI - It pre-dates 5G units and $MOBILE

**Comment by Chief-Zach** [comment]
I’m using the bobcat 300. Light miner just like I believe is is supported.
I looked through your code for a minute and didn’t find any super obvious
errors so I’m unsure.

**Comment by co8** [comment]
Yes, Bobcat 300 is supported. I'm seeing errors in my cron.log as well, but am also receiving valid activity in HDS. Helium's public API does not always return a valid response because it's often overloaded. I'd recommend to leave it running. Keep me posted.

**Comment by Chief-Zach** [comment]
Could you possible add some try except statements in with a timeout to try
to remedy the issue? something like try 5 times and if they still fail than
pass and throw an error?

**Comment by co8** [comment]
Absolutely , you're welcome to submit a PR
